<?php
/** @var $block \MageSuite\BackInStock\Block\Product\View\Stock */
/** @var \MageSuite\BackInStock\ViewModel\Product $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->canRenderBackInStockForm()) :?>
    <?php $placeholder = $block->getEmailInputPlaceholder() ?>
    <form class="form cs-product-stock-subscription <?= /* @noEscape */ $block->getAdditionalCssClasses() ?> cs-buybox__stock-subscription"
        novalidate
        action="<?= /* @noEscape */ $block->getActionUrl();?>"
        method="post"
        data-mage-init='{
            "MageSuite_BackInStock/js/back-in-stock": {
                "loaderIcon": "<?= /* @noEscape */ $block->getViewFileUrl($block->getLoaderIconPath()) ?>"
            }
        }'
    >
        <div class="cs-product-stock-subscription__msg">
            <div class="message cs-messages__message"><div class="cs-messages__text"></div></div>
        </div>
        <?= $block->getChildHtml('configurables.introduction') ?>
        <?= $block->getChildHtml('product.backinstock.subscription.hotspot.aboveemail') ?>
        <fieldset class="fieldset">
            <div class="field cs-product-stock-subscription__field">
                <label class="label cs-product-stock-subscription__label" for="email"><?= /* @noEscape */ $block->getEmailLabel() ?></label>
                <input type="hidden" name="product_id" id="product_id" value="<?= /* @noEscape */ $viewModel->getProductId();?>"/>
                <div class="cs-product-stock-subscription__input-wrapper">
                    <input class="input-text cs-product-stock-subscription__input" 
                           data-validate="{required:true, 'validate-email':true}" 
                           title="<?= /* @noEscape */ $block->getEmailLabel() ?>"
                           type="text" 
                           name="email" 
                           id="email"
                           <?php if ($placeholder) : ?> placeholder="<?= /* @noEscape */ $placeholder ?>"<?php endif ?>
                    />
                </div>
                <button type="submit" class="action submit primary cs-product-stock-subscription__submit">
                    <span class="cs-product-stock-subscription__submit-label"><?= /* @noEscape */ $block->getSubmitLabel() ?></span>
                    <?= $block->getChildHtml('product.backinstock.subscription.icon'); ?>
                </button>
            </div>
        </fieldset>
    </form>
<?php endif;?>
