<?php $notifications = $block->getNotifications(); ?>
<?php if ($notifications && count($notifications)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Notification requests') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Name') ?></th>
                <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Request Date') ?></th>
                <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Stock Status') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($notifications as $notification): ?>
                <?php $product = $block->getProduct($notification->getProductId());?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col id"><?= /* @escapeNotVerified */ $product->getSku() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                        <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="action view" target="_blank">
                            <span><?= /* @escapeNotVerified */ $product->getName() ?></span>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Request Date')) ?>" class="col date"><?= $block->formatDate($notification->getAddDate()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Stock Status')) ?>" class="col status"><?php echo $product->getIsSalable() ? __('In Stock') : __('Out of Stock') ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getUnsubscribeUrl($notification) ;?>" class="action view">
                            <span><?php echo $notification->getStatus() ? __('Delete') : __('Unsubscribe') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have no back in stock subscriptions yet.') ?></span></div>
<?php endif ?>
