<?php
/** @var \MageSuite\BackInStock\Block\Subscriptions\History $block */
/** @var \MageSuite\BackInStock\ViewModel\Subscriptions\History $viewModel */
$viewModel = $block->getViewModel();
$subscriptions = $viewModel->getSubscriptions();

if (count($subscriptions)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @noEscape */ __('Notification requests') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= /* @noEscape */ __('SKU') ?></th>
                <th scope="col" class="col date"><?= /* @noEscape */ __('Name') ?></th>
                <th scope="col" class="col shipping"><?= /* @noEscape */ __('Request Date') ?></th>
                <th scope="col" class="col shipping"><?= /* @noEscape */ __('Stock Status') ?></th>
                <th scope="col" class="col actions"><?= /* @noEscape */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $subscription) : ?>
                <?php $productData = $viewModel->getProductData($subscription);?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col id"><?= /* @noEscape */ $productData->getSku() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                        <a href="<?= /* @noEscape */ $productData->getProductUrl() ?>" class="action view" target="_blank">
                            <span><?= /* @noEscape */ $productData->getName() ?></span>
                        </a>
                    </td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Request Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($subscription->getAddDate()) ?></td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Stock Status')) ?>" class="col status"><?= /* @noEscape */ $viewModel->isProductSaleable($subscription) ? __('In Stock') : __('Out of Stock') ?></td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= /* @noEscape */ $viewModel->getUnsubscribeUrl($subscription) ;?>" class="action view">
                            <span><?= /* @noEscape */ __('Unsubscribe') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= /* @noEscape */ __('You have no back in stock subscriptions yet.') ?></span></div>
<?php endif ?>
