<?php
/**
 * Template changed in order to allow back in stock functionality for grouped products
 * - out-of-stock class added (line 38)
 * - data-simple-id added (line 48)
 * - grouped.item.outofstock.spot added (line 64)
 */

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $product = $block->getProduct(); ?>
<?php $associatedProducts = $block->getAssociatedProducts(); ?>
<?php $hasAssociatedProducts = count($associatedProducts) > 0; ?>

<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{"Magento_GroupedProduct/js/product-ids-resolver": {}}'>
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= $block->escapeHtml(__('Product Name')) ?></th>
            <?php if ($product->isSaleable()) : ?>
                <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($hasAssociatedProducts) : ?>
        <tbody>
            <?php foreach ($associatedProducts as $item) : ?>
                <tr class="associated-product <?= !$item->isSaleable() ? 'out-of-stock' : '' ?>" data-simple-id="<?= $block->escapeHtmlAttr($item->getId()) ?>">
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                    <strong class="product-item-name"><?= $block->escapeHtml($item->getName()) ?></strong>
                    <?php if ($block->getCanShowProductPrice($product)) : ?>
                        <?php if ($block->getCanShowProductPrice($item)) : ?>
                            <?= /* @noEscape */ $block->getProductPrice($item) ?>
                        <?php endif; ?>
                        <?php endif; ?>
                </td>
                <?php if ($product->isSaleable()) : ?>
                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" data-simple-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="col qty">
                    <?php if ($item->isSaleable()) : ?>
                    <div class="control qty">
                        <input type="number"
                               name="super_group[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                               data-selector="super_group[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                               value="<?= $block->escapeHtmlAttr($item->getQty() * 1) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                    </div>
                <?php else : ?>
                    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </div>
                    <?= $block->getChildHtml('grouped.item.outofstock.spot') ?>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
                <?php if ($block->getCanShowProductPrice($product)
                && $block->getCanShowProductPrice($item)
                && trim($block->getProductPriceHtml(
                    $item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))) : ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
        <?php else : ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($product->isSaleable()) : ?>4<?php else : ?>3<?php endif; ?>">
                    <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
